10. Используя модуль `array` и  библиотеку `numpy`, решить следующие задачи:<br>а) Дан массив $A$ размера $N$. Сформировать новый массив B того же размера по следующему правилу: элемент BK равен сумме элементов массива $A$ с номерами от $K$ до $N$.<br>б) Дана матрица размера $M×N$. Упорядочить ее строки так, чтобы их первые элементы образовывали возрастающую последовательность.


In [3]:
import array
import numpy as np

# Создаем массив A размера N
N = 5
A = array.array('i', range(N))  # Массив целых чисел от 0 до N-1

# Создаем новый массив B размера N
B = np.zeros(N, dtype=int)

# Считаем элементы массива B по заданному правилу
for k in range(N):
    B[k] = np.sum(A[k:])

# Выводим результат
print(B)

[10 10  9  7  4]


б) Дана матрица размера  M×N . Упорядочить ее строки так, чтобы их первые элементы образовывали возрастающую последовательность.

In [9]:
import array
import numpy as np

# Создаем матрицу размера M×N
M = 3
N = 4
A = np.array([[151235, 3, 5, 7],
              [2, 4, 4356, 8],
              [9, 11, 13, 1515]])

# Сортируем строки матрицы по первым элементам
A = A[np.argsort(A[:, 0])]

# Выводим результат
print(A)



[[     2      4   4356      8]
 [     9     11     13   1515]
 [151235      3      5      7]]


Реализовать класс стек через использование списка:

Создать класс Stack с методами:
push(item): добавляет элемент item в верхушку стека;
pop(): удаляет и возвращает элемент из верхушки стека;
peek(): возвращает элемент из верхушки стека без его удаления;
is_empty(): проверяет, пуст ли стек;
size(): возвращает текущий размер стека.
Дан стек. Необходимо проверить, является ли его содержимое последовательностью арифметической прогрессии.

In [14]:
class Stack:
    def __init__(self):
        self.items = []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        if not self.is_empty():
            return self.items.pop()
        else:
            return None

    def peek(self):
        if not self.is_empty():
            return self.items[-1]
        else:
            return None

    def is_empty(self):
        return len(self.items) == 0

    def size(self):
        return len(self.items)
    def __str__(self):
        return str(self.items)

# Проверяем, является ли содержимое стека арифметической прогрессией
def is_arithmetic_progression(stack):
    if stack.size() < 3:
        return True
    diff = stack.pop() - stack.peek()

    while not stack.is_empty() and stack.size() != 1:
        current_diff = stack.pop() - stack.peek()
        if current_diff != diff:
            return False

    return True



stack = Stack()
stack.push(1)
stack.push(3)
stack.push(5)
stack.push(7)

print(is_arithmetic_progression(stack))

stack.pop()
stack.push(9)
stack.push(5)
stack.push(2)

print(is_arithmetic_progression(stack))  # False

True
False


In [19]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
class Stack:
    def __init__(self):
        self.top = None
        self.size = 0

    def push(self, item):
        new_node = Node(item)
        new_node.next = self.top
        self.top = new_node
        self.size += 1

    def pop(self):
        if not self.is_empty():
            popped_item = self.top.data
            self.top = self.top.next
            self.size -= 1
            return popped_item
        else:
            return None

    def peek(self):
        if not self.is_empty():
            return self.top.data
        else:
            return None

    def is_empty(self):
        return self.size == 0

    def Size(self):
        return self.size
    
def is_arithmetic_progression(stack):
    if stack.Size() < 3:
        return True

    diff = stack.pop() - stack.peek()
    while not stack.is_empty()  and stack.Size() != 1:
        current_diff = stack.pop() - stack.peek()
        if current_diff != diff:
            return False

    return True

stack = Stack()
stack.push(1)
stack.push(3)
stack.push(5)
stack.push(7)

print(is_arithmetic_progression(stack))  # True

stack.pop()
stack.push(9)
stack.push(8)
stack.push(5)

print(is_arithmetic_progression(stack))  # False


True
False


Создать класс Queue с методами:
enqueue(item): добавляет элемент item в конец очереди;
dequeue(): удаляет и возвращает элемент из начала очереди;
peek(): возвращает элемент из начала очереди без его удаления;
is_empty(): проверяет, пуста ли очередь;
size(): возвращает текущий размер очереди.

Создать класс очереди, который будет хранить только элементы определенного типа данных. Тип элементов задается при инициализации объекта класса очереди. При добавлении элемента, если его тип не соответствует заданному, то он не должен добавляться.

In [20]:
class TypedQueue:
    def __init__(self, element_type):
        self.element_type = element_type
        self.items = []

    def enqueue(self, item):
        if isinstance(item, self.element_type):
            self.items.append(item)
        else:
            raise ValueError(f"Очередь ожидает элементы типа {self.element_type}, а не {type(item)}")

    def dequeue(self):
        if not self.is_empty():
            return self.items.pop(0)
        else:
            return None

    def peek(self):
        if not self.is_empty():
            return self.items[0]
        else:
            return None

    def is_empty(self):
        return len(self.items) == 0

    def size(self):
        return len(self.items)
# Создаем очередь для хранения строк
string_queue = TypedQueue(str)

# Добавляем строки в очередь
string_queue.enqueue("Hello")
string_queue.enqueue("World")
string_queue.enqueue("!")

# Выводим элементы из очереди
print(string_queue.dequeue())  # Выведет "Hello"
print(string_queue.dequeue())  # Выведет "World"
print(string_queue.dequeue())  # Выведет "!"


# Пытаемся добавить число в очередь
try:
    string_queue.enqueue(123)
except ValueError as e:
    print(e)  # Выведет "Очередь ожидает элементы типа <class 'str'>, а не <class 'int'>"


Hello
World
!
Очередь ожидает элементы типа <class 'str'>, а не <class 'int'>


In [21]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
class Queue:
    def __init__(self):
        self.head = None
        self.tail = None
        self.size = 0

    def enqueue(self, item):
        new_node = Node(item)
        if self.is_empty():
            self.head = new_node
            self.tail = new_node
        else:
            self.tail.next = new_node
            self.tail = new_node
        self.size += 1

    def dequeue(self):
        if not self.is_empty():
            popped_item = self.head.data
            self.head = self.head.next
            if self.head is None:
                self.tail = None
            self.size -= 1
            return popped_item
        else:
            return None

    def peek(self):
        if not self.is_empty():
            return self.head.data
        else:
            return None

    def is_empty(self):
        return self.size == 0

    def size(self):
        return self.size

class TypedQueue:
    def __init__(self, element_type):
        self.element_type = element_type
        self.queue = Queue()

    def enqueue(self, item):
        if isinstance(item, self.element_type):
            self.queue.enqueue(item)
        else:
            raise ValueError(f"Очередь ожидает элементы типа {self.element_type}, а не {type(item)}")

    def dequeue(self):
        return self.queue.dequeue()

    def peek(self):
        return self.queue.peek()

    def is_empty(self):
        return self.queue.is_empty()

    def size(self):
        return self.queue.size()
    
# Создаем очередь для хранения строк
string_queue = TypedQueue(str)

# Добавляем строки в очередь
string_queue.enqueue("Hello")
string_queue.enqueue("World")
string_queue.enqueue("!")

# Выводим элементы из очереди
print(string_queue.dequeue())  # Выведет "Hello"
print(string_queue.dequeue())  # Выведет "World"
print(string_queue.dequeue())  # Выведет "!"


# Пытаемся добавить число в очередь
try:
    string_queue.enqueue(123)
except ValueError as e:
    print(e)  # Выведет "Очередь ожидает элементы типа <class 'str'>, а не <class 'int'>"


Hello
World
!
Очередь ожидает элементы типа <class 'str'>, а не <class 'int'>
